username = input('Введите имя: ')
title = input('Заголовок: ')
content = input('Описание: ')
status = input ('Состояние задачи: ')
create_date = input('Дата начала д.м.г: ')
issue_date = input('Дата окончания: д.м.г: ')
#print(username)
#print(username[0:7])
#print(title )
#print(content)
#print(status)
#print(create_date)
#print(issue_date)
#print(create_date[0:18])
#print(issue_date[0:21])
print(f'Имя: {username}.')
print(f'Заголовок: {title}.')
print(f'Описание: {content}.')
print(f'Состояние задачи: {status}.')
print(f'Дата начала: {create_date[0:6]}')
print(f'Дата окончание: {issue_date[0:6]}')